apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  labels:
    app: oracle
spec:
  type: ClusterIP
  selector:
    app: oracle
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
