apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage # Önceki adımda belirttiğimiz namespace
data:
  # Ayarlar: Görsel ve genel yapı
  settings.yaml: |
    title: Homelab Ops Center
    background: https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070
    cardBlur: sm
    theme: dark
    layout:
      Sistem Durumu:
        style: row
        columns: 4
      Altyapı & GitOps:
        style: row
        columns: 3
      Uygulamalar:
        style: row
        columns: 3

  # Widgetlar: Cluster'ın anlık durumunu izlemek için
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showNodeData: true
    - search:
        provider: google
        focus: true
    - datetime:
        format:
          timeStyle: short
          dateStyle: long
        hour12: false

  # Servisler: Uygulamalarına hızlı erişim
  services.yaml: |
    - Sistem Durumu:
        - K3s Cluster:
            icon: kubernetes.png
            widget:
              type: kubernetes
              showDetails: true
        - DockerHub:
            icon: docker.png
            href: https://hub.docker.com/u/yavuzkaramert
            description: Image Registry

    - Altyapı & GitOps:
        - ArgoCD:
            icon: argocd.svg
            href: http://argocd.local
            description: GitOps Engine
        - GitHub Repo:
            icon: github.png
            href: https://github.com/yavuzkaramert/homilab-ops
            description: Ops Repository

    - Uygulamalar:
        - Oracle App: # Az önce kurduğumuz uygulama
            icon: fastapi.png
            href: http://oracle.homelab.local
            description: Konteyner Bilgelik Servisi
            ping: http://oracle-service.default.svc.cluster.local/health # İçten kontrol

  # Boş ama gerekli dosyalar
  kubernetes.yaml: ""
  bookmarks.yaml: ""
  custom.css: ""
  docker.yaml: ""