apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-sa
  namespace: homepage # Dashboard'un çalıştığı namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-cluster-reader
rules:
  - apiGroups: [""]
    # Dashboard'un sadece bu kaynakları görmesi yeterlidir
    resources: ["nodes", "pods", "namespaces", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"] # CPU/RAM metrikleri için (Metrics Server kuruluysa)
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-binding
subjects:
  - kind: ServiceAccount
    name: homepage-sa
    namespace: homepage
roleRef:
  kind: ClusterRole
  name: homepage-cluster-reader
  apiGroup: rbac.authorization.k8s.io