apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage # Önceki adımlarla uyumlu olması için kritik
  labels:
    app: homepage
    tier: frontend
spec:
  # ClusterIP: Ingress arkasında çalışan servisler için en güvenli ve standart tip
  type: ClusterIP
  ports:
  - name: http
    port: 80           # Ingress'in servise ulaşacağı port
    targetPort: 3000   # Pod içindeki uygulamanın (Homepage) dinlediği port
    protocol: TCP
  selector:
    # Deployment'taki 'spec.template.metadata.labels' ile birebir eşleşmeli
    app: homepage